help:
	@echo "Commands:"
	@echo " - help: 	show this help"
	@echo " - new:		create a new AoC solution for today"
setup:
	@touch session.cookie
	@mkdir -p inputs
	@make help

new:
	@python3 src/utils/new_day.py